name: buildCI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
    DOTNETVERSION: 8.0.100-rc.2.23502.2

jobs:
  buildMauiApp:
    runs-on: macos-13
    
    steps:
      - uses: actions/checkout@v2

      - name: Install .NET 8
        shell: bash
        run: |
          curl -o dotnet-install.sh -sSL https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh
          sh dotnet-install.sh --version ${{env.DOTNETVERSION}}
          dotnet --list-sdks  

      - name: List installed .NET info
        shell: pwsh
        run: dotnet --info

      - name: Install .NET MAUI
        shell: bash
        run: |
          dotnet workload install maui macos ios wasm-tools
    
      - name: Restore nuget packages
        run: |
          dotnet restore CincoDemo.sln

      - name: Run Unit Test
        shell: bash
        run: |
          cd CincoApp.Tests/
          dotnet test CincoApp.Tests.csproj --logger "trx;LogFileName=test-results.trx" --configuration Debug --collect:"XPlat Code Coverage"

      - name: Test Reporter
        uses: dorny/test-reporter@v1.7.0
        if: success() || failure()
        with:
          name: Unit Test Report
          path: CincoDemo/CincoApp.Tests/TestResults/*.trx
          reporter: dotnet-trx
      

      - name: Build MacCatalyst
        shell: bash
        run: |
          cd CincoApp.Maui/
          dotnet publish -f net8.0-maccatalyst -c Release -p:BuildIpa=True

      - name: Build Android
        shell: bash
        run: |
          cd CincoApp.Maui/
          dotnet publish -f net8.0-android -c Release
          
      - uses: actions/upload-artifact@v2
        with:
          name: artifacts-binaries
          path: |
            **/*.pkg
            **/*.apk
      
